import React, { useState } from 'react';
import {
  Brain,
  Send,
  Sparkles,
  RotateCcw,
  Zap,
  Coins,
  ArrowRight,
  Download,
} from 'lucide-react';
import { fetchDiagnoseRepair, fetchMicroLesson, fetchRoadmap, fetchStudyPrioritySummary } from '../../services/api';

interface ChatMessage {
  id: string;
  sender: 'bot' | 'user';
  text: string;
  timestamp: string;
  type?: 'roadmap' | 'lesson' | 'quiz' | 'diagnosis' | 'repair' | 'summary' | 'guardrail';
  partData?: {
    partNumber: number;
    partTitle: string;
    importance: 'high' | 'medium' | 'low';
    examAdvice: string;
    content: string;
    quizQuestion: {
      id: string;
      question: string;
      options?: string[];
      correctAnswer: string;
      explanation: string;
    };
  };
  diagnosisData?: {
    errorType: 'Mistake' | 'Misconception' | 'Knowledge gap';
    diagnosticExplanation: string;
    repairContent: string;
    improved: boolean;
  };
}

interface DedicatedChatbotProps {
  onRewardXp: (amount: number, stickerTitle?: string) => void;
}

const downloadChatbotRepairPdf = (repair: any, topicName: string) => {
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>EduMind AI – Active Recall Study Guide (${topicName})</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;900&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Inter', sans-serif; background: #0f172a; color: #f8fafc; padding: 40px; line-height: 1.7; }
  .header { background: #1e3a8a; color: white; padding: 32px; border-radius: 16px; margin-bottom: 32px; border: 1px solid rgba(255,255,255,0.2); }
  .header h1 { font-size: 28px; font-weight: 900; margin-bottom: 8px; }
  .header p { font-size: 14px; opacity: 0.9; }
  .badge { display: inline-block; background: #2563eb; color: white; padding: 6px 14px; border-radius: 20px; font-size: 12px; font-weight: 700; margin-bottom: 12px; }
  .section { background: white; border: 1px solid #e2e8f0; border-radius: 14px; padding: 24px; margin-bottom: 20px; color: #1e293b; }
  .section h2 { font-size: 17px; font-weight: 800; color: #1e3a8a; margin-bottom: 12px; }
  .section p, .section li { font-size: 14px; color: #334155; }
  .formula-box { background: #fffbeb; border: 2px solid #f59e0b; border-radius: 14px; padding: 24px; margin-bottom: 20px; }
  .formula-box h2 { color: #92400e; }
  .formula-box p { color: #78350f; font-weight: 600; font-size: 15px; }
  .tips-box { background: #ecfdf5; border: 2px solid #10b981; border-radius: 14px; padding: 24px; margin-bottom: 20px; }
  .tips-box h2 { color: #065f46; }
  .tips-box li { color: #065f46; font-weight: 500; margin-bottom: 6px; }
  .footer { text-align: center; margin-top: 32px; font-size: 12px; color: #64748b; }
</style>
</head>
<body>
  <div class="header">
    <div class="badge">🧠 ACTIVE RECALL STUDY GUIDE</div>
    <h1>EduMind AI – ${topicName.toUpperCase()} Repair Guide</h1>
    <p>Generated by AI Chatbot Engine • ${new Date().toLocaleDateString('en-US')}</p>
  </div>
  <div class="section">
    <h2>🔍 Diagnostic Diagnosis (${repair.errorType || 'Concept Gap'})</h2>
    <p>${repair.diagnosticExplanation || ''}</p>
  </div>
  <div class="section">
    <h2>🛠️ 3-Minute Micro-Repair Lesson</h2>
    <p>${repair.microRepairContent || ''}</p>
  </div>
  <div class="formula-box">
    <h2>📐 Improvement Formula (Step-by-Step)</h2>
    <p>${repair.improvementFormula || ''}</p>
  </div>
  <div class="tips-box">
    <h2>🧠 Active Recall Strategies</h2>
    <ul>
      ${(repair.activeRecallTips || []).map((tip: string) => `<li>• ${tip}</li>`).join('\n      ')}
    </ul>
  </div>
  <div class="footer">
    <p>Review this study guide in 24 hours for spaced repetition mastery • EduMind AI</p>
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `EduMind_${topicName.replace(/\s+/g, '_')}_Study_Guide.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const DedicatedChatbot: React.FC<DedicatedChatbotProps> = ({ onRewardXp }) => {
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: 'init_1',
      sender: 'bot',
      text: `👋 **Welcome to your EduMind AI Step-by-Step Learning Chatbot!**\n\nI break complex exam topics into **small, part-wise micro-lessons** so your brain learns without burnout.\n\nType any exam or study topic below (e.g. *"I have exam teach me computer network"* or *"Explain SN1 vs SN2 in Organic Chemistry"*).`,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    },
  ]);

  const [inputQuery, setInputQuery] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [activeTopic, setActiveTopic] = useState<string | null>(null);
  const [activePartIndex, setActivePartIndex] = useState<number>(0);
  const [partsList, setPartsList] = useState<any[]>([]);
  const [userSelectedAnswer, setUserSelectedAnswer] = useState<string>('');
  const [coinsEarned, setCoinsEarned] = useState<number>(50);


  type TopicCheck = { ok: true } | { ok: false; reason: 'greeting' | 'too_short' | 'off_topic' };

  const GREETING_PATTERNS = [
    /^h+i+!*$/, /^h+e+y+a?!*$/, /^h+e+l+o+!*$/, /^hello+!*$/, /^y+o+!*$/, /^sup!*$/,
    /^(good\s?)?(morning|afternoon|evening|night)!*$/, /^(what'?s up|wassup|whats up)!*$/,
    /^(thanks?|thank you|thx|ty)!*$/, /^(ok|okay|k|kk|cool|nice|great)!*$/, /^(bye|goodbye|see ya)!*$/,
    /^(test|testing)!*$/,
  ];

  const NON_EDU_KEYWORDS = [
    'football', 'cricket', 'pizza', 'movie', 'celebrity', 'gossip',
    'weather', 'politics', 'joke', 'song', 'game score', 'dating', 'fashion',
  ];

  const checkTopic = (rawText: string): TopicCheck => {
    const text = rawText.trim();
    const lower = text.toLowerCase();

    if (GREETING_PATTERNS.some((p) => p.test(lower))) {
      return { ok: false, reason: 'greeting' };
    }

    const meaningfulChars = lower.replace(/[^a-z0-9]/g, '');
    if (meaningfulChars.length < 3) {
      return { ok: false, reason: 'too_short' };
    }

    const hasNonEdu = NON_EDU_KEYWORDS.some((k) => lower.includes(k));
    const hasEduOverride = /(exam|study|math|science|learn|homework|course|syllabus)/.test(lower);
    if (hasNonEdu && !hasEduOverride) {
      return { ok: false, reason: 'off_topic' };
    }

    return { ok: true };
  };

  const handleSendMessage = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!inputQuery.trim()) return;

    const userText = inputQuery.trim();
    setInputQuery('');

    const userMsg: ChatMessage = {
      id: `u_${Date.now()}`,
      sender: 'user',
      text: userText,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    };

    setMessages((prev) => [...prev, userMsg]);

    const lastMsg = messages[messages.length - 1];
    const isTopicCommand = /^(teach|explain|learn|show|walk|i have (an? )?exam)/i.test(userText.trim());
    const isAnsweringQuiz = !isTopicCommand && activeTopic !== null && !!(lastMsg?.partData?.quizQuestion);

    if (!isAnsweringQuiz) {
      const topicCheck = checkTopic(userText);

      if (topicCheck.ok === false) {
        const reason = topicCheck.reason;
        const reply =
          reason === 'greeting'
            ? `👋 Hey there! I'm not a small-talk chatbot — I'm built to turn a real study topic into a part-by-part lesson plan.\n\nTry something like *"teach me computer networks"*, *"SN1 vs SN2 reactions"*, or *"explain binary search trees"* and I'll get started.`
            : reason === 'too_short'
            ? `🤔 That's a bit too short for me to build a lesson plan from. Give me a real subject or concept — e.g. *"photosynthesis"*, *"Newton's laws of motion"*, *"SQL joins"* — and I'll break it into parts.`
            : `🛡️ I'm focused on academic & STEM study topics (e.g., Computer Networks, Organic Chemistry, Data Structures, Calculus, Physics). Try rephrasing with "study" or "exam" if this is actually coursework — otherwise, give me a real topic!`;

        setTimeout(() => {
          setMessages((prev) => [
            ...prev,
            {
              id: `guard_${Date.now()}`,
              sender: 'bot',
              type: 'guardrail',
              text: reply,
              timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            },
          ]);
        }, 400);
        return;
      }
    }

    setIsLoading(true);

    if (isAnsweringQuiz && lastMsg && lastMsg.partData) {
      await handleEvaluateAnswer(userText, lastMsg.partData);
      setIsLoading(false);
      return;
    }

    try {
      const topicName =
        userText
          .replace(/^(i have (an? )?exam[,]?\s*)?(please\s*)?(can you\s*)?(teach|explain|help me (understand|learn)|show me|walk me through)\s*/i, '')
          .replace(/^(me\s+)?(about\s+)?/i, '')
          .trim() || userText;
      setActiveTopic(topicName);

      const roadmapData = await fetchRoadmap(topicName);
      const roadmapSteps = roadmapData.roadmap || [];

      if (roadmapSteps.length === 0) {
        setMessages((prev) => [
          ...prev,
          {
            id: `err_${Date.now()}`,
            sender: 'bot',
            text: `⚠️ I couldn't generate a roadmap for "${topicName}". Try rephrasing with more detail (e.g., *"teach me OSI model in computer networks"*).`,
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          },
        ]);
        setIsLoading(false);
        return;
      }

      setPartsList(roadmapSteps);
      setActivePartIndex(0);

      const firstStep = roadmapSteps[0] || { stepNumber: 1, title: `Introduction to ${topicName}` };
      const lesson = await fetchMicroLesson(topicName, firstStep.title, 1, roadmapSteps.length || 5);

      const part1Data = {
        partNumber: 1,
        partTitle: firstStep.title,
        importance: (firstStep.stepNumber === 1 || firstStep.stepNumber === 4 ? 'high' : 'medium') as 'high' | 'medium',
        examAdvice: firstStep.stepNumber === 1 || firstStep.stepNumber === 4
          ? '🔥 HIGH EXAM PRIORITY: Guaranteed 10-15 Marks on core definitions & packet flows.'
          : '📌 MEDIUM PRIORITY: Important background for multi-part synthesis problems.',
        content: lesson.content,
        quizQuestion: lesson.checkQuestions?.[0] || {
          id: 'q1',
          question: `What is the primary function of ${firstStep.title}?`,
          options: [
            'Establishes structured rules for data transmission',
            'Completely replaces physical server cables',
            'Encrypts all web browser cookies automatically',
            'Eliminates latency in long-distance networks',
          ],
          correctAnswer: 'Establishes structured rules for data transmission',
          explanation: 'Standardized protocols govern how data packets travel safely across network layers.',
        },
      };

      setMessages((prev) => [
        ...prev,
        {
          id: `b_road_${Date.now()}`,
          sender: 'bot',
          type: 'roadmap',
          text: `📚 **Part-Wise Study Plan Generated for: "${topicName.toUpperCase()}"**\n\nHere are your bite-sized study parts:\n` +
            roadmapSteps.map((s: any, idx: number) => `• **Part ${idx + 1}**: ${s.title} (${idx === 0 ? '🔥 High Yield' : '📌 Core Topic'})`).join('\n') +
            `\n\nLet's tackle **Part 1** right now!`,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        },
        {
          id: `b_part1_${Date.now()}`,
          sender: 'bot',
          type: 'lesson',
          partData: part1Data,
          text: `📖 **Part 1 of ${roadmapSteps.length}: ${part1Data.partTitle}**\n\n` +
            `${part1Data.examAdvice}\n\n` +
            `${part1Data.content}\n\n` +
            `💡 **Real-World Analogy**: ${lesson.analogy || 'Think of it like a mail postal code system guiding letters to their exact destination.'}`,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        },
      ]);
    } catch (err) {
      console.error(err);
      setMessages((prev) => [
        ...prev,
        {
          id: `err_${Date.now()}`,
          sender: 'bot',
          text: `⚠️ I had a temporary glitch generating parts. Let's try again!`,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        },
      ]);
    } finally {
      setIsLoading(false);
    }
  };

  const normalize = (s: string) => s.toLowerCase().replace(/[^\w\s]/g, '').replace(/\s+/g, ' ').trim();

  const handleEvaluateAnswer = async (userAnswer: string, partData: any) => {
    const q = partData.quizQuestion;
    if (!q) return;

    const normalizedAnswer = normalize(userAnswer);
    const normalizedCorrect = normalize(q.correctAnswer);

    const pickedCorrectOption =
      !!q.options && q.options.some((opt: string) => normalize(opt) === normalizedAnswer && opt === q.correctAnswer);

    const correctWords = normalizedCorrect.split(' ').filter((w) => w.length > 3);
    const overlapCount = correctWords.filter((w) => normalizedAnswer.includes(w)).length;
    const wordOverlapMatch = correctWords.length > 0 && overlapCount / correctWords.length >= 0.6;

    const isCorrect =
      pickedCorrectOption ||
      normalizedAnswer === normalizedCorrect ||
      normalizedAnswer.includes(normalizedCorrect) ||
      wordOverlapMatch;

    if (isCorrect) {
      onRewardXp(50, `Mastered ${partData.partTitle}`);
      setCoinsEarned((prev) => prev + 15);

      const nextPartIdx = activePartIndex + 1;

      if (nextPartIdx < partsList.length) {
        setActivePartIndex(nextPartIdx);
        const nextStep = partsList[nextPartIdx];

        try {
          const lesson = await fetchMicroLesson(activeTopic || 'Study Topic', nextStep.title, nextPartIdx + 1, partsList.length);

          const nextPartData = {
            partNumber: nextPartIdx + 1,
            partTitle: nextStep.title,
            importance: (nextPartIdx === 3 ? 'high' : 'medium') as 'high' | 'medium',
            examAdvice: nextPartIdx === 3
              ? '🔥 HIGH EXAM PRIORITY: Crucial for numerical calculation questions.'
              : '📌 MEDIUM PRIORITY: High probability for short answer questions.',
            content: lesson.content,
            quizQuestion: lesson.checkQuestions?.[0] || {
              id: `q_${nextPartIdx}`,
              question: `Which concept dictates execution in ${nextStep.title}?`,
              correctAnswer: 'Layered Protocol Standards',
              explanation: 'Protocols dictate step-by-step handshakes.',
            },
          };

          setMessages((prev) => [
            ...prev,
            {
              id: `diag_yes_${Date.now()}`,
              sender: 'bot',
              type: 'diagnosis',
              diagnosisData: {
                errorType: 'Mistake',
                diagnosticExplanation: `🎯 **BRILLIANT! 100% Correct!** You nailed the answer: "${userAnswer}".`,
                repairContent: `+50 XP Earned! 🪙 +15 Gold Coins claimed!`,
                improved: true,
              },
              text: `✅ **PERFECT ANSWER!**\n\n+50 XP Earned! 🪙 +15 Gold Coins added to your wallet!\n\nUnlocking **Part ${nextPartIdx + 1}**...`,
              timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            },
            {
              id: `part_next_${Date.now()}`,
              sender: 'bot',
              type: 'lesson',
              partData: nextPartData,
              text: `📖 **Part ${nextPartIdx + 1} of ${partsList.length}: ${nextPartData.partTitle}**\n\n` +
                `${nextPartData.examAdvice}\n\n` +
                `${nextPartData.content}\n\n` +
                `💡 **Analogy**: ${lesson.analogy || 'Like traffic lights at a busy intersection keeping cars moving smoothly.'}`,
              timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            },
          ]);
        } catch (err) {
          console.error(err);
          setMessages((prev) => [
            ...prev,
            {
              id: `err_${Date.now()}`,
              sender: 'bot',
              text: `⚠️ Failed to load Part ${nextPartIdx + 1}. Please try again.`,
              timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            },
          ]);
        }
      } else {
        try {
          const summary = await fetchStudyPrioritySummary(activeTopic || 'Exam Topic');

          setMessages((prev) => [
            ...prev,
            {
              id: `diag_finish_${Date.now()}`,
              sender: 'bot',
              type: 'summary',
              text: `🎉 **TOPIC COMPLETE: ${activeTopic?.toUpperCase()} MASTERED!**\n\n` +
                `Here is your final **Exam Priority Breakdown** (What to study vs what to skip):\n\n` +
                `🔥 **MUST STUDY (80% Exam Weight)**:\n` +
                (summary.highYieldTopics?.map((h: any) => `• **${h.title}**: ${h.reason}`).join('\n') || '• Review all core concepts') +
                `\n\n💤 **LOW YIELD (Can Skip / Glance Only)**:\n` +
                (summary.lowYieldTopics?.map((l: any) => `• ${l.title}`).join('\n') || '• Advanced edge cases') +
                `\n\n🌙 **Night Before Exam Checklist**:\n` +
                (summary.nightBeforeChecklist?.map((c: string) => `✅ ${c}`).join('\n') || '✅ Review key formulas and definitions'),
              timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            },
          ]);
        } catch (err) {
          console.error(err);
          setMessages((prev) => [
            ...prev,
            {
              id: `err_${Date.now()}`,
              sender: 'bot',
              text: `🎉 **TOPIC COMPLETE!** You mastered all parts. Great job!`,
              timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            },
          ]);
        }
      }
    } else {
      try {
        const repair = await fetchDiagnoseRepair(
          partData.partTitle,
          q.question,
          userAnswer,
          q.correctAnswer
        );

        const tipsText = (repair.activeRecallTips || [])
          .map((tip: string, idx: number) => `  ${idx + 1}. ${tip}`)
          .join('\n');

        setMessages((prev) => [
          ...prev,
          {
            id: `diag_no_${Date.now()}`,
            sender: 'bot',
            type: 'repair',
            diagnosisData: {
              errorType: repair.errorType,
              diagnosticExplanation: repair.diagnosticExplanation,
              repairContent: repair.microRepairContent,
              improved: false,
            },
            text: `🔍 **AI DIAGNOSIS: ${repair.errorType.toUpperCase()} DETECTED**\n\n` +
              `${repair.diagnosticExplanation}\n\n` +
              `🛠️ **3-Minute Micro-Repair Lesson**:\n` +
              `${repair.microRepairContent}\n\n` +
              `📐 **Improvement Formula**:\n` +
              `${repair.improvementFormula}\n\n` +
              `🧠 **Active Recall Strategies**:\n` +
              `${tipsText}\n\n` +
              `🔄 **Teaching Style Changed**: Try this follow-up Recall Challenge:`,
            partData: {
              ...partData,
              repairLesson: repair,
              quizQuestion: repair.recallChallenge || {
                id: `recall_${Date.now()}`,
                question: `Now that we repaired this gap, what governs the transmission in ${partData.partTitle}?`,
                correctAnswer: partData.quizQuestion.correctAnswer,
              },
            },
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          },
        ]);
      } catch (err) {
        console.error(err);
        setMessages((prev) => [
          ...prev,
          {
            id: `err_${Date.now()}`,
            sender: 'bot',
            text: `❌ That's not quite right. The correct answer was: **${q.correctAnswer}**.\n\n${q.explanation}\n\nLet's move forward when you're ready.`,
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          },
        ]);
      }
    }
  };

  return (
    <div className="bg-slate-900 border border-blue-800 rounded-3xl shadow-2xl p-4 sm:p-6 space-y-4 text-white flex flex-col min-h-[600px] max-w-4xl mx-auto">

      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 border-b border-blue-900/80 pb-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-2xl bg-blue-600 flex items-center justify-center text-white font-black shadow-sm border border-blue-500">
            <Brain className="w-6 h-6 text-amber-300 animate-pulse" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="font-extrabold text-lg text-white">Step-by-Step AI Learning Chatbot</h2>
              <span className="bg-amber-500/20 text-amber-300 text-[10px] font-black px-2 py-0.5 rounded-full border border-amber-400/30 uppercase">
                EXAM GUARDRAIL
              </span>
            </div>
            <p className="text-xs text-blue-300 font-medium">Part-wise materials, diagnostic repairs & mini challenges</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <span className="flex items-center gap-1 text-xs font-black text-amber-400 bg-amber-500/10 px-3 py-1 rounded-xl border border-amber-400/30">
            <Coins className="w-4 h-4 text-amber-400" />
            🪙 {coinsEarned} Gold Coins
          </span>
          <button
            onClick={() => {
              setMessages([
                {
                  id: 'init_reset',
                  sender: 'bot',
                  text: `👋 Chatbot reset! Ask me any study topic (e.g. *"I have exam teach me computer network"*).`,
                  timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
                },
              ]);
              setActiveTopic(null);
              setActivePartIndex(0);
              setPartsList([]);
            }}
            className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 transition-colors cursor-pointer"
            title="Reset Chat"
          >
            <RotateCcw className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Chat Messages Stream */}
      <div className="flex-1 overflow-y-auto space-y-4 pr-1 scrollbar-thin scrollbar-thumb-blue-800 max-h-[500px]">
        {messages.map((msg) => {
          const isBot = msg.sender === 'bot';

          return (
            <div
              key={msg.id}
              className={`flex flex-col ${isBot ? 'items-start' : 'items-end'} space-y-1`}
            >
              <div className="flex items-center gap-2 text-[10px] text-slate-400 font-bold px-1">
                <span>{isBot ? '🤖 EduMind AI Tutor' : '👤 Student'}</span>
                <span>• {msg.timestamp}</span>
              </div>

              <div
                className={`max-w-[88%] p-4 rounded-2xl text-xs sm:text-sm font-medium leading-relaxed whitespace-pre-wrap ${
                  isBot
                    ? 'bg-slate-950 border border-blue-900/80 text-slate-200 shadow-md'
                    : 'bg-blue-700 text-white border border-amber-400/40 shadow-md font-semibold'
                }`}
              >
                {msg.text}

                {(msg.type === 'repair' || msg.partData?.repairLesson) && (
                  <div className="mt-3 pt-3 border-t border-blue-900/80 flex items-center justify-between">
                    <span className="text-[11px] font-bold text-amber-300">
                      📄 Active Recall Study Guide Generated
                    </span>
                    <button
                      onClick={() =>
                        downloadChatbotRepairPdf(
                          msg.partData?.repairLesson || {
                            errorType: msg.diagnosisData?.errorType || 'Concept Gap',
                            diagnosticExplanation: msg.diagnosisData?.diagnosticExplanation || msg.text,
                            microRepairContent: msg.diagnosisData?.repairContent || msg.text,
                            improvementFormula: 'Step 1: Read → Step 2: Cover → Step 3: Write → Step 4: Check → Step 5: Spaced Review',
                            activeRecallTips: [
                              'Cover the answer and try to recall from memory.',
                              'Draw a concept mind-map without looking at notes.',
                              'Explain this topic in 30 seconds to a friend.',
                            ],
                          },
                          activeTopic || 'Study Topic'
                        )
                      }
                      className="px-3 py-1.5 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 text-xs font-black flex items-center gap-1.5 transition-all cursor-pointer shadow-md"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>Download Study Guide (PDF)</span>
                    </button>
                  </div>
                )}

                {msg.partData && msg.partData.quizQuestion && (
                  <div className="mt-4 pt-3 border-t border-blue-900/80 space-y-3 bg-blue-950/60 p-3.5 rounded-xl border border-blue-800">
                    <div className="flex items-center justify-between text-xs font-black text-amber-400 uppercase tracking-wide">
                      <span className="flex items-center gap-1">
                        <Zap className="w-4 h-4 text-amber-400" />
                        Mini Challenge (Recall Game)
                      </span>
                      <span className="text-[10px] text-emerald-400 bg-emerald-500/20 px-2 py-0.5 rounded-full border border-emerald-500/30">
                        +50 XP Reward
                      </span>
                    </div>

                    <p className="font-bold text-white">{msg.partData.quizQuestion.question}</p>

                    {msg.partData.quizQuestion.options && (
                      <div className="grid grid-cols-1 gap-2 pt-1">
                        {msg.partData.quizQuestion.options.map((opt: string, idx: number) => (
                          <button
                            key={idx}
                            onClick={() => {
                              setUserSelectedAnswer(opt);
                              handleEvaluateAnswer(opt, msg.partData);
                            }}
                            className="text-left px-3.5 py-2 rounded-xl bg-slate-900 hover:bg-blue-900 border border-blue-800 hover:border-amber-400 text-xs font-bold text-slate-200 hover:text-amber-300 transition-all cursor-pointer flex items-center justify-between group"
                          >
                            <span>{opt}</span>
                            <ArrowRight className="w-3.5 h-3.5 text-slate-500 group-hover:text-amber-400 group-hover:translate-x-1 transition-transform" />
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                )}
              </div>
            </div>
          );
        })}

        {isLoading && (
          <div className="flex items-center gap-2 text-xs font-bold text-amber-400 bg-slate-950 p-3 rounded-2xl border border-blue-900 w-fit animate-pulse">
            <Sparkles className="w-4 h-4 text-amber-400 animate-spin" />
            <span>EduMind AI is diagnosing concept & crafting micro-lesson...</span>
          </div>
        )}
      </div>

      {/* Input Form Bar */}
      <form onSubmit={handleSendMessage} className="pt-2 border-t border-blue-900/80 flex items-center gap-2">
        <input
          type="text"
          value={inputQuery}
          onChange={(e) => setInputQuery(e.target.value)}
          placeholder='Ask a topic e.g. "I have exam teach me computer network"'
          className="flex-1 bg-slate-950 border border-blue-800 focus:border-amber-400 rounded-2xl px-4 py-3 text-xs sm:text-sm font-medium text-white placeholder-slate-500 outline-none transition-all shadow-inner"
        />

        <button
          type="submit"
          disabled={isLoading || !inputQuery.trim()}
          className="bg-blue-600 hover:bg-blue-500 disabled:bg-slate-700 disabled:cursor-not-allowed text-white rounded-2xl text-xs sm:text-sm py-3 px-5 flex items-center gap-2 cursor-pointer shrink-0 shadow-md font-extrabold transition-colors"
        >
          <Send className="w-4 h-4" />
          <span className="hidden sm:inline">Ask AI</span>
        </button>
      </form>
    </div>
  );
};