import React, { useState } from 'react';
import { RepairLesson } from '../../types';
import { Wrench, CheckCircle, ArrowRight, ShieldAlert, Sparkles, Brain, Download, BookOpen, Lightbulb } from 'lucide-react';

interface DiagnoseRepairCardProps {
  repairLesson: RepairLesson;
  onCompleteRepair: (isSuccess: boolean) => void;
}

/** Generate and download a PDF-style study guide as an HTML file */
const downloadRepairPdf = (repair: RepairLesson) => {
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>EduMind AI – Active Recall Study Guide</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;900&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Inter', sans-serif; background: #f8fafc; color: #1e293b; padding: 40px; line-height: 1.7; }
  .header { background: #1e3a8a; color: white; padding: 32px; border-radius: 16px; margin-bottom: 32px; }
  .header h1 { font-size: 28px; font-weight: 900; margin-bottom: 8px; }
  .header p { font-size: 14px; opacity: 0.85; }
  .badge { display: inline-block; background: #2563eb; color: white; padding: 6px 14px; border-radius: 20px; font-size: 13px; font-weight: bold; margin-bottom: 16px; }
  .section { background: white; border: 1px solid #e2e8f0; padding: 24px; border-radius: 14px; margin-bottom: 24px; }
  .section h2 { font-size: 18px; font-weight: 800; color: #1e293b; margin-bottom: 12px; display: flex; align-items: center; gap: 8px; }
  .section h2 .icon { font-size: 20px; }
  .section p, .section li { font-size: 14px; color: #334155; }
  .section ul { padding-left: 20px; }
  .section li { margin-bottom: 8px; }
  .step-num { display: inline-flex; width: 28px; height: 28px; background: #2563eb; color: white; border-radius: 50%; justify-content: center; align-items: center; font-weight: bold; margin-right: 12px; font-size: 14px; }
  .formula-box { background: #fffbeb; border: 2px solid #f59e0b; border-radius: 14px; padding: 24px; margin-bottom: 20px; }
  .formula-box h2 { color: #92400e; }
  .formula-box p { color: #78350f; font-weight: 600; font-size: 15px; }
  .tips-box { background: #ecfdf5; border: 2px solid #10b981; border-radius: 14px; padding: 24px; margin-bottom: 20px; }
  .tips-box h2 { color: #065f46; }
  .tips-box li { color: #064e3b; font-weight: 500; }
  .recall-box .question { font-size: 16px; font-weight: 700; color: #4c1d95; margin: 12px 0; }
  .recall-box .answer { background: white; padding: 12px 16px; border-radius: 10px; border: 1px solid #c4b5fd; margin-top: 8px; }
  .footer { text-align: center; margin-top: 32px; font-size: 12px; color: #94a3b8; }
  @media print { body { padding: 20px; } .section, .formula-box, .tips-box, .recall-box { break-inside: avoid; } }
</style>
</head>
<body>
  <div class="header">
    <div class="badge">🧠 ACTIVE RECALL STUDY GUIDE</div>
    <h1>EduMind AI – Personalized Repair Guide</h1>
    <p>Generated by AI diagnostic engine • ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
  </div>

  <div class="section">
    <h2><span class="icon">🔍</span> Error Diagnosis: ${repair.errorType}</h2>
    <p>${repair.diagnosticExplanation}</p>
  </div>

  <div class="section">
    <h2><span class="icon">🛠️</span> 3-Minute Micro Repair Lesson</h2>
    <p>${repair.microRepairContent}</p>
  </div>

  <div class="formula-box">
    <h2><span class="icon">📐</span> Improvement Formula (Step-by-Step)</h2>
    <p>${repair.improvementFormula}</p>
  </div>

  <div class="tips-box">
    <h2><span class="icon">🧠</span> Active Recall Strategies</h2>
    <ul>
      ${repair.activeRecallTips.map(tip => `<li>${tip}</li>`).join('\n      ')}
    </ul>
  </div>

  <div class="recall-box">
    <h2><span class="icon">⚡</span> Self-Test Recall Challenge</h2>
    <div class="question">Q: ${repair.recallChallenge.question}</div>
    <div class="answer">
      <strong>Answer:</strong> ${repair.recallChallenge.correctAnswer}<br/>
      <strong>Explanation:</strong> ${repair.recallChallenge.explanation}
    </div>
  </div>

  <div class="footer">
    <p>📖 Review this guide in 24 hours for spaced repetition • Generated by EduMind AI</p>
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `EduMind_Repair_Guide_${Date.now()}.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const DiagnoseRepairCard: React.FC<DiagnoseRepairCardProps> = ({
  repairLesson,
  onCompleteRepair,
}) => {
  const [recallAnswer, setRecallAnswer] = useState('');
  const [isAnswered, setIsAnswered] = useState(false);
  const [isCorrect, setIsCorrect] = useState(false);

  const getErrorTypeBadge = (type: string) => {
    switch (type) {
      case 'Careless mistake':
        return { label: '🎯 Careless Mistake', bg: 'bg-amber-100', text: 'text-amber-800' };
      case 'Misconception':
        return { label: '🧠 Concept Misconception', bg: 'bg-purple-100', text: 'text-purple-800' };
      default:
        return { label: '📚 Knowledge Gap', bg: 'bg-rose-100', text: 'text-rose-800' };
    }
  };

  const badge = getErrorTypeBadge(repairLesson.errorType);

  const handleVerifyRecall = () => {
    const isRight = recallAnswer.trim().length > 0;
    setIsCorrect(isRight);
    setIsAnswered(true);
  };

  return (
    <div className="sketch-card bg-rose-50/40 border border-rose-200 p-6 sm:p-8 space-y-6">
      {/* Diagnosis Banner */}
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-rose-600 text-white rounded-2xl shadow-xs">
            <ShieldAlert className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className={`text-xs font-bold px-2.5 py-0.5 rounded-full ${badge.bg} ${badge.text}`}>
                {badge.label}
              </span>
              <span className="text-xs font-medium text-slate-500">3-Minute Repair Mode</span>
            </div>
            <h3 className="font-bold text-xl text-slate-900">Diagnose → Repair → Recall Loop</h3>
          </div>
        </div>

        {/* Download PDF Button */}
        <button
          onClick={() => downloadRepairPdf(repairLesson)}
          className="flex items-center gap-2 px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold transition-all cursor-pointer shadow-md"
        >
          <Download className="w-4 h-4" />
          Download Study Guide
        </button>
      </div>

      {/* Diagnostic Explanation */}
      <div className="p-4 bg-white rounded-2xl border border-slate-200/80 shadow-2xs">
        <h4 className="font-bold text-xs text-slate-400 uppercase mb-1">AI Diagnostic Feedback</h4>
        <p className="text-sm font-semibold text-slate-800 leading-relaxed">
          {repairLesson.diagnosticExplanation}
        </p>
      </div>

      {/* 3-Minute Micro Repair Lesson */}
      <div className="p-5 bg-amber-50/90 rounded-2xl border border-amber-200/80 relative">
        <div className="flex items-center gap-2 mb-2">
          <Wrench className="w-5 h-5 text-amber-700" />
          <h4 className="font-bold text-base text-amber-950">Micro-Repair Lesson (Targeted Gap Fix)</h4>
        </div>
        <p className="text-sm text-amber-900 font-medium leading-relaxed">
          {repairLesson.microRepairContent}
        </p>
      </div>

      {/* Improvement Formula */}
      <div className="p-5 bg-gradient-to-br from-orange-50 to-amber-50 rounded-2xl border border-orange-200/80">
        <div className="flex items-center gap-2 mb-3">
          <Lightbulb className="w-5 h-5 text-orange-600" />
          <h4 className="font-bold text-base text-orange-950">📐 Improvement Formula</h4>
        </div>
        <p className="text-sm text-orange-900 font-semibold leading-relaxed">
          {repairLesson.improvementFormula}
        </p>
      </div>

      {/* Active Recall Tips */}
      <div className="p-5 bg-emerald-50 rounded-2xl border border-emerald-200">
        <div className="flex items-center gap-2 mb-3">
          <Brain className="w-5 h-5 text-emerald-600" />
          <h4 className="font-bold text-base text-emerald-950">🧠 Active Recall Strategies</h4>
        </div>
        <ul className="space-y-2">
          {repairLesson.activeRecallTips.map((tip, idx) => (
            <li key={idx} className="flex items-start gap-2.5 text-sm text-emerald-900 font-medium">
              <span className="w-6 h-6 rounded-full bg-emerald-200 text-emerald-800 text-xs font-black flex items-center justify-center shrink-0 mt-0.5">
                {idx + 1}
              </span>
              <span>{tip}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* Recall Challenge */}
      <div className="p-5 bg-white rounded-2xl border border-slate-200/80 shadow-2xs space-y-4">
        <div className="flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-emerald-600" />
          <h4 className="font-bold text-base text-slate-900">Mini Recall Challenge (Lock in Mastery)</h4>
        </div>

        <p className="font-semibold text-sm text-slate-800">{repairLesson.recallChallenge.question}</p>

        {!isAnswered ? (
          <div className="space-y-3">
            <input
              type="text"
              placeholder="Type your revised answer..."
              value={recallAnswer}
              onChange={(e) => setRecallAnswer(e.target.value)}
              className="w-full p-3 rounded-xl border border-slate-200 font-medium text-sm focus:bg-slate-50 focus:border-indigo-400 outline-none transition-all"
            />
            <button
              disabled={!recallAnswer.trim()}
              onClick={handleVerifyRecall}
              className="btn-sketch-mint text-xs flex items-center gap-2 disabled:opacity-50"
            >
              Verify Recall & Lock In
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>
        ) : (
          <div className="space-y-3">
            <div className="p-4 bg-emerald-50 rounded-xl border border-emerald-300 text-emerald-900 font-bold text-sm flex items-center gap-2">
              <CheckCircle className="w-5 h-5 text-emerald-600 shrink-0" />
              <span>Great job! Gap repaired and concept mastered (+30 XP)!</span>
            </div>
            <p className="text-xs text-slate-600 font-medium">{repairLesson.recallChallenge.explanation}</p>

            <div className="flex items-center gap-3">
              <button
                onClick={() => onCompleteRepair(true)}
                className="btn-sketch-primary text-xs flex items-center gap-2"
              >
                Continue to Next Question
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
              <button
                onClick={() => downloadRepairPdf(repairLesson)}
                className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-indigo-50 hover:bg-indigo-100 text-indigo-700 text-xs font-bold border border-indigo-200 transition-all cursor-pointer"
              >
                <BookOpen className="w-3.5 h-3.5" />
                Save Study Guide
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
